name: Generate Sitemap

on:
  push:
    branches: [main]  # or 'master', if that's your default
  workflow_dispatch:  # allows you to trigger it manually

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Run sitemap generator
        run: |
          node scripts/generate-sitemap.js

      - name: Commit and push sitemap
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add sitemap.xml
          git commit -m "Auto-generate sitemap"
          git push